title       = "sunrisesunset"
baseURL     = "https://sunrisesunset-cli.tamnd.com/"
description = "A command line for the Sunrise-Sunset API."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/sunrisesunset-cli"
